#!/bin/bash
set -euo pipefail

# ================================================================
# run-train-more.sh
# Fine-tune CodeGPT on mixed dataset: BCB(10% balanced) + Other Domain (e.g., Camel)
#
# Inputs:
#   ../dataset/train_mix.txt
#   ../dataset/valid_mix.txt
#   ../dataset/test_<otherdomain>.txt   (OTHER-domain-only test, e.g., test_camel.txt)
#   ../dataset/mix/data.jsonl           (loaded via --test_type mix)
#
# Key args:
#   --test_type mix        -> makes run.py load ../dataset/mix/data.jsonl
#   --subsample_ratio 1.0  -> use full mixed data (do NOT subsample again)
#
# Notes:
#   - Train/Valid are MIXED (BCB + other domain).
#   - Test is OTHER-DOMAIN ONLY to measure cross-domain generalization.
# ================================================================

echo ">>> [System Config] Detecting Hardware..."

# Count available GPUs
NUM_GPUS=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)

# Hyperparameters
PER_GPU_BATCH=8
TARGET_GLOBAL_BATCH=64
EPOCHS=2

# Calculate Gradient Accumulation Steps: 64 / (8 * Num_GPUs)
ACCUM_STEPS=$(( TARGET_GLOBAL_BATCH / (PER_GPU_BATCH * NUM_GPUS) ))
[ "$ACCUM_STEPS" -lt 1 ] && ACCUM_STEPS=1

echo "    - GPUs Detected : $NUM_GPUS"
echo "    - Per-GPU Batch : $PER_GPU_BATCH"
echo "    - Accumulation  : $ACCUM_STEPS"
echo "    - Global Batch  : $TARGET_GLOBAL_BATCH"
echo "    - Epochs        : $EPOCHS"

# Launch command (single vs multi GPU)
LAUNCH_CMD="accelerate launch"
[ "$NUM_GPUS" -gt 1 ] && LAUNCH_CMD="$LAUNCH_CMD --multi_gpu --num_processes $NUM_GPUS"

# --- Configuration ---
PROJECT="azure"
OUTDIR="./saved_models_mix_${PROJECT}"
mkdir -p "$OUTDIR"

# Input Files (Parameterized)
# Other-domain test file (generated by 2_mix_data.py)
TEST_FILE="../dataset/test_${PROJECT}.txt"
TRAIN_FILE="../dataset/train_mix_${PROJECT}.txt"
VALID_FILE="../dataset/valid_mix_${PROJECT}.txt"

# Sanity checks
[ -f "$TEST_FILE" ]  || { echo "ERROR: Missing test file: $TEST_FILE"; exit 1; }
[ -f "$TRAIN_FILE" ] || { echo "ERROR: Missing train file: $TRAIN_FILE"; exit 1; }

echo ">>> [Start] Fine-tuning on mixed dataset (BCB10% + ${PROJECT})"
echo "    - Output Dir : $OUTDIR"
echo "    - Log File   : $OUTDIR/train_mix_${PROJECT}.log"
echo "    - Train      : $TRAIN_FILE"
echo "    - Valid      : $VALID_FILE"
echo "    - Test (OD)  : $TEST_FILE"

$LAUNCH_CMD run.py \
  --output_dir="$OUTDIR/" \
  --subsample_ratio 1.0 \
  --model_type=gpt2 \
  --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 \
  --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 \
  --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 \
  --test_type mix_azure \
  --do_train \
  --do_test \
  --train_data_file="$TRAIN_FILE" \
  --eval_data_file="$VALID_FILE" \
  --test_data_file="$TEST_FILE" \
  --block_size 400 \
  --train_batch_size "$PER_GPU_BATCH" \
  --gradient_accumulation_steps "$ACCUM_STEPS" \
  --eval_batch_size 32 \
  --epoch "$EPOCHS" \
  --learning_rate 5e-5 \
  --max_grad_norm 1.0 \
  --evaluate_during_training \
  --save_steps 500 \
  --logging_steps 100 \
  --save_total_limit 2 \
  --overwrite_output_dir \
  --seed 3 2>&1 | tee "$OUTDIR/train_mix_${PROJECT}.log"
