mkdir ./saved_models_combined/
python run.py \
    --output_dir=./saved_models_combined/ \
    --subsample_ratio 1.0 \
    --model_type=roberta \
    --config_name=microsoft/graphcodebert-base \
    --model_name_or_path=microsoft/graphcodebert-base \
    --tokenizer_name=microsoft/graphcodebert-base \
    --do_train \
    --do_test \
    --train_data_file=../dataset/combined_org10_plus_repos/train_mix.txt \
    --eval_data_file=../dataset/combined_org10_plus_repos/valid_mix.txt \
    --test_data_file=../dataset/org/test.txt \
    --epoch 2 \
    --code_length 384 \
    --data_flow_length 128 \
    --train_batch_size 16 \
    --eval_batch_size 32 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 3 2>&1| tee ./saved_models_combined/train_combined_org10_plus_repos.log
